GRID_SIZE = 12 #max 24x24, min 8x8
MINES_NUMBER = (GRID_SIZE ** 2) // 4
CELL_WIDTH = 35
CELL_HEIGHT = 35
BUTTON_FRAME = 6
MARGIN_BETWEEN_BUTTONS = 4
MAP_BUTTON_MARGIN = 2
RESET_BUTTON_MARGIN = 4
WIDTH = (CELL_WIDTH+BUTTON_FRAME) * GRID_SIZE
TOP_FRAME = 50
HEIGHT = TOP_FRAME + (GRID_SIZE * CELL_HEIGHT + (GRID_SIZE*BUTTON_FRAME))
CELL_COUNT = GRID_SIZE**2



