CELL_SIZE = 35
BUTTON_FRAME = 6
MARGIN_BETWEEN_BUTTONS = 4
MAP_BUTTON_MARGIN = 2
RESET_BUTTON_MARGIN = 4
WIDTH = (CELL_SIZE + BUTTON_FRAME)
HEIGHT = (CELL_SIZE+BUTTON_FRAME)
SETTINGS_WIDTH = 400
SETTINGS_HEIGHT = 200

